name: pipeline

on:
  push:
    branches: [ master ]
    
env:
  PATH_TO_CSPROJ: src/UmbracoProject/UmbracoProject.csproj
  PROJECT_ALIAS: jams-cicd-project
  CLOUD_KEY: ${{ secrets.API_KEY }}
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      DEPLOYMENT_ID: ${{ steps.deploymentMeta.outputs.deploymentId }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Install Dependencies
        run: dotnet restore $PATH_TO_CSPROJ
        
      - name: Build
        run: dotnet build $PATH_TO_CSPROJ --configuration Release --no-restore
        
      - name: Test
        run: dotnet test $PATH_TO_CSPROJ --no-restore --verbosity normal
        
      - id: deploymentMeta
        name: Create Deployment Meta
        run: scripts/create_deployment.sh $PROJECT_ALIAS $CLOUD_KEY BuildNumber1234
        shell: bash
      
      - name: show Deployment Id  
        run: echo ${{ needs.build.outputs.DEPLOYMENT_ID }}
        
      - name: Zip Source Code
        run: git archive --format=zip HEAD -o packed/sources.zip
        shell: bash
        
      - name: Post Zipped Artifact
        run: scripts/upload_package.sh $PROJECT_ALIAS ${{ needs.build.outputs.DEPLOYMENT_ID }} $CLOUD_KEY packed/sources.zip
        shell: bash
        
      - name: Wait for deployment completed
        run: scripts/get_deployment_status.sh $PROJECT_ALIAS ${{ needs.build.outputs.DEPLOYMENT_ID }} $CLOUD_KEY
        shell: bash
      
