name: pipeline

on:
  push:
    branches: [ master ]
    
env:
  PATH_TO_CSPROJ: src/UmbracoProject/UmbracoProject.csproj
  PROJECT_ALIAS: jams-cicd-project
  CLOUD_KEY: ${{ secrets.API_KEY }}
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
#      - name: Install Dependencies
#        run: dotnet restore $PATH_TO_CSPROJ
        
#      - name: Build
#        run: dotnet build $PATH_TO_CSPROJ --configuration Release --no-restore
        
#      - name: Test
#        run: dotnet test $PATH_TO_CSPROJ --no-restore --verbosity normal
        
      - id: deployment-meta
        name: Create Deployment Meta
        uses: jesp209i/uc-prepare-deployment-action@v0.0.3-beta5
        with:
          project-alias: $PROJECT_ALIAS
          cloud-api-key: $CLOUD_KEY
          commit-message: BuildNumber1234
      
      - name: show Deployment Id  
        run: echo "${{ steps.deployment-meta.outputs.DEPLOYMENT_ID}}"
        
      - name: Zip Source Code
        run: zip -r sources.zip . -x ".git/*" ".github/*" "scripts/*" "src/UmbracoProject/bin/*" "src/UmbracoProject/obj/*"
        shell: bash
        
      - name: Post Zipped Artifact
        run: scripts/upload_package.sh $PROJECT_ALIAS ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} $CLOUD_KEY $GITHUB_WORKSPACE/sources.zip
        shell: bash
        
      - name: Wait for deployment completed
        run: scripts/get_deployment_status.sh $PROJECT_ALIAS ${{ steps.deployment-meta.outputs.DEPLOYMENT_ID }} $CLOUD_KEY
        shell: bash
      
