name: pwsh pipeline

# Trigger when committing to main branch
on:
  push:
    branches:
      - do-not-run

jobs:
  # Try to sync the local repository to get up to speed with any changes in Cloud project
  cloud-sync:
    name: "Syncronize with Cloud"
    uses: ./.github/workflows/pwsh-cloud-sync.yml
    with:
      cloudBaseUrl: ${{ vars.CLOUD_BASE_URL }}
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: cloud-sync
    uses: ./.github/workflows/pwsh-cloud-deployment.yml
    with:
      newSha: ${{ needs.cloud-sync.outputs.newSha }}
      cloudBaseUrl: ${{ vars.CLOUD_BASE_URL }}
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      UMBRACO_CLOUD_API_KEY: ${{ secrets.UMBRACO_CLOUD_API_KEY }}